Client setup
dz0o0/Taltner pull request #23
Opened 2024-05-24 05:31 UTC by dz0o0

## 概要

## 変更内容

## 関連Issue, PR

## その他

2024-05-24 06:33 UTC, KorRyu3 commented
@dz0o0 
node_modulesはgitの管理から外して、かつ`client/`に入れて欲しいなぁと思ったり

2024-05-24 06:36 UTC, KorRyu3 commented
package.json系も`client/`に入れてくれると、ファイルの影響範囲の見通しが良くなって嬉しいなぁと

2024-05-25 00:03 UTC, nka21 commented
あれれ、clientディレクトリ内でinstallしてたら、clientディレクトリ外でnode_moduleもpackage.jsonもできることはないと思うんだけど、もしかしてディレクトリ違ってたんじゃない？あららw

2024-05-25 00:14 UTC, nka21 reviewed
このコミットでインストールしてるPrettierが `/client`ディレクトリの外で入れちゃってるなぁ。。。
prettier uninstall一回して、`/client`ディレクトリ内でprettierインストールし直せば解決しそうかな？

2024-05-25 00:15 UTC, nka21 requested changes
こういう場合、Request changesでreviewすればいいんかな？
<img width="673" alt="image" src="https://github.com/dz0o0/Taltner/assets/133028205/750441b0-cca1-4f78-b3b5-cd98589a8064">

2024-05-25 07:14 UTC, dz0o0 commented
@KorRyu3 @nka21 
適切な場所に変更したんだけどどう？

2024-05-25 08:14 UTC, KorRyu3 approved these changes
`.vscode/settings.json`の拡張機能について

2024-05-25 08:14 UTC, KorRyu3 commented on .vscode/settings.json
> +    "editor.defaultFormatter": "esbenp.prettier-vscode",
`esbenp.prettier-vscode`っていうのはvscodeの拡張機能かな？
拡張機能使うなら、`devcontainer.json`の`extensions`にも追記しといてね~~

2024-05-25 08:14 UTC, KorRyu3 commented on .vscode/settings.json
> +    "editor.defaultFormatter": "esbenp.prettier-vscode",
ただ、全体に関わってくるわけでもないし、今回はやらなくてもいいかも

2024-05-26 00:25 UTC, nka21 approved these changes

2024-05-26 00:25 UTC, merged